name: firebase_task_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  
  cloud_firestore: ^5.6.1
  equatable: ^2.0.3

  file_picker: ^8.3.1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.6
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo_foreground.png
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
